# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "yearly"
  - package-ecosystem: "npm"
    directory: "/blockly"
    schedule:
      interval: "yearly"
  - package-ecosystem: "npm"
    directory: "/test-mineflayer"
    schedule:
      interval: "yearly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "yearly"
