FROM docker.io/library/ubuntu:23.04 as build

RUN apt-get update -y

# https://github.com/OASIS-learn-study/minecraft-storeys-maker/pull/429
RUN apt-get install -y openjdk-11-jdk curl \
                libgtk-3-0 libasound2 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 \
                libxrandr2 libxrender1 libxtst6 libpangocairo-1.0-0 libpango-1.0-0 \
                libatk1.0-0 libcairo-gobject2 libcairo2 libgdk-pixbuf-2.0-0 \
                libglib2.0-0 libdbus-glib-1-2 libdbus-1-3 libxcb-shm0 \
                libx11-xcb1 libxcb1 libxcursor1 libxi6

# https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs && node --version

WORKDIR /project

# This will cache the Gradle distribution in the image
COPY gradle /project/gradle
COPY gradlew /project/
RUN ./gradlew --version
