FROM docker.io/library/ubuntu:22.04 as build

RUN apt-get update -y

RUN apt-get install -y openjdk-11-jdk curl

# https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs && node --version

WORKDIR /project

# This will cache the Gradle distribution in the image
COPY gradle /project/gradle
COPY gradlew /project/
RUN ./gradlew --version
