#!/usr/bin/env bash
set -euox pipefail

./make

podman stop --time 7 storeys || true

podman run --name storeys --detach --rm \
    -e OPS=73551f35-7acb-45c0-bc65-8083c53eec69,fb79c1a9-72bd-34dc-9775-c2ac868d7ccf \
    -e ONLINE_MODE=FALSE \
    -v $PWD/minecraft-server-test-data:/data:Z -e UID=0 -e GID=0 \
    -p 25565:25565 -p 8080:8080 -p 7070:7070 minecraft-storeys-maker

podman logs -f storeys &

RETRIES=30
until podman healthcheck run storeys; do
  RETRIES=$(($RETRIES - 1))
    if [ $RETRIES -eq 0 ]; then
        echo "Minecraft container failed to become healthy, giving up now"
        exit 1
    fi
    sleep 1
done

./gradlew test-mineflayer:npmTest

# podman stop storeys

# Note that `-e UID=0 -e GID=0` makes `itzg/minecraft-server`'s processes run as `root`
# (instead of its default UID/GID `1000` which is hard-coded in its `setup-user.sh`),
# and that (somewhat counter intuitively) will actually run as your unprivileged user on the host,
# see https://github.com/itzg/docker-minecraft-server#running-as-alternate-usergroup-id
# and https://github.com/containers/podman/blob/v2.2.1/docs/tutorials/rootless_tutorial.md#using-volumes.

# TODO HOW-TO --userns keep-id
# NOT --uidmap=0:100000:65536 --uidmap=1000:100000:65536 --gidmap=1000:100000:65536 --gidmap=0:100000:65536
# NOT --userns=host --user=$(id -un):$(id -gn)
